' TODO:
'
' * Fix up all internal references
' * Make it check that all *this_that* things are indeed defined in the grammar, and log just the *this*
' * Make a better "report error" thing, and distinguish fatal from non-fatal (e.g. duplicate section title)
' * Be more aggressive about trimming plural grammar products, particularly in the namespaces, and change plurals into the "A (',' A)*" pattern
' * Restore grammar from places where I removed duplicates, and reference the original location
' * Factor into a VB "grammar2html" library, a C# "colorize-csharp" NuGet + command-line util, and md2docx
' * Make the hyperlinked grammar show its popups again

Module Module1

    Sub UpdateMDs(fns As IEnumerable(Of String))
        For Each fn In fns
            Console.WriteLine(fn)
            Dim s = IO.File.ReadAllText(fn)
            s = s.Replace("§19.4.2", "[Resulting XML](documentation-comments.md#resulting-xmlexpressions.md#addition-operator)")
            s = s.Replace("§19.4.1", "[C# source code](documentation-comments.md#c-source-codeexpressions.md#addition-operator)")
            s = s.Replace("§19.4", "[An example](documentation-comments.md#an-exampleexpressions.md#addition-operator)")
            s = s.Replace("§19.3.2", "[ID string examples](documentation-comments.md#id-string-examplesexpressions.md#addition-operator)")
            s = s.Replace("§19.3.1", "[ID string format](documentation-comments.md#id-string-formatexpressions.md#addition-operator)")
            s = s.Replace("§19.3", "[Processing the documentation file](documentation-comments.md#processing-the-documentation-fileexpressions.md#addition-operator)")
            s = s.Replace("§19.2.18", "[<typeparamref>](documentation-comments.md#typeparamrefexpressions.md#addition-operator)")
            s = s.Replace("§19.2.17", "[<typeparam>](documentation-comments.md#typeparamexpressions.md#addition-operator)")
            s = s.Replace("§19.2.16", "[<value>](documentation-comments.md#valueexpressions.md#addition-operator)")
            s = s.Replace("§19.2.15", "[<summary>](documentation-comments.md#summaryexpressions.md#addition-operator)")
            s = s.Replace("§19.2.14", "[<seealso>](documentation-comments.md#seealsoexpressions.md#addition-operator)")
            s = s.Replace("§19.2.13", "[<see>](documentation-comments.md#seeexpressions.md#addition-operator)")
            s = s.Replace("§19.2.12", "[<returns>](documentation-comments.md#returnsexpressions.md#addition-operator)")
            s = s.Replace("§19.2.11", "[<remark>](documentation-comments.md#remarkexpressions.md#addition-operator)")
            s = s.Replace("§19.2.10", "[<permission>](documentation-comments.md#permissionexpressions.md#addition-operator)")
            s = s.Replace("§19.2.9", "[<paramref>](documentation-comments.md#paramrefexpressions.md#addition-operator)")
            s = s.Replace("§19.2.8", "[<param>](documentation-comments.md#paramexpressions.md#addition-operator)")
            s = s.Replace("§19.2.7", "[<para>](documentation-comments.md#paraexpressions.md#addition-operator)")
            s = s.Replace("§19.2.6", "[<list>](documentation-comments.md#listexpressions.md#addition-operator)")
            s = s.Replace("§19.2.5", "[<include>](documentation-comments.md#includeexpressions.md#addition-operator)")
            s = s.Replace("§19.2.4", "[<exception>](documentation-comments.md#exceptionexpressions.md#addition-operator)")
            s = s.Replace("§19.2.3", "[<example>](documentation-comments.md#exampleexpressions.md#addition-operator)")
            s = s.Replace("§19.2.2", "[<code>](documentation-comments.md#codeexpressions.md#addition-operator)")
            s = s.Replace("§19.2.1", "[<c>](documentation-comments.md#cexpressions.md#addition-operator)")
            s = s.Replace("§19.2", "[Recommended tags](documentation-comments.md#recommended-tagsexpressions.md#addition-operator)")
            s = s.Replace("§19.1", "[Introduction](documentation-comments.md#introductionexpressions.md#addition-operator)")
            s = s.Replace("§19", "[Documentation comments](documentation-comments.md#documentation-commentsexpressions.md#addition-operator)")
            s = s.Replace("§18.9", "[Dynamic memory allocation](unsafe-code.md#dynamic-memory-allocationexpressions.md#addition-operator)")
            s = s.Replace("§18.8", "[Stack allocation](unsafe-code.md#stack-allocationexpressions.md#addition-operator)")
            s = s.Replace("§18.7.3", "[Definite assignment checking](unsafe-code.md#definite-assignment-checkingexpressions.md#addition-operator)")
            s = s.Replace("§18.7.2", "[Fixed size buffers in expressions](unsafe-code.md#fixed-size-buffers-in-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§18.7.1", "[Fixed size buffer declarations](unsafe-code.md#fixed-size-buffer-declarationsexpressions.md#addition-operator)")
            s = s.Replace("§18.7", "[Fixed size buffers](unsafe-code.md#fixed-size-buffersexpressions.md#addition-operator)")
            s = s.Replace("§18.6", "[The fixed statement](unsafe-code.md#the-fixed-statementexpressions.md#addition-operator)")
            s = s.Replace("§18.5.8", "[The sizeof operator](unsafe-code.md#the-sizeof-operatorexpressions.md#addition-operator)")
            s = s.Replace("§18.5.7", "[Pointer comparison](unsafe-code.md#pointer-comparisonexpressions.md#addition-operator)")
            s = s.Replace("§18.5.6", "[Pointer arithmetic](unsafe-code.md#pointer-arithmeticexpressions.md#addition-operator)")
            s = s.Replace("§18.5.5", "[Pointer increment and decrement](unsafe-code.md#pointer-increment-and-decrementexpressions.md#addition-operator)")
            s = s.Replace("§18.5.4", "[The address-of operator](unsafe-code.md#the-address-of-operatorexpressions.md#addition-operator)")
            s = s.Replace("§18.5.3", "[Pointer element access](unsafe-code.md#pointer-element-accessexpressions.md#addition-operator)")
            s = s.Replace("§18.5.2", "[Pointer member access](unsafe-code.md#pointer-member-accessexpressions.md#addition-operator)")
            s = s.Replace("§18.5.1", "[Pointer indirection](unsafe-code.md#pointer-indirectionexpressions.md#addition-operator)")
            s = s.Replace("§18.5", "[Pointers in expressions](unsafe-code.md#pointers-in-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§18.4.1", "[Pointer arrays](unsafe-code.md#pointer-arraysexpressions.md#addition-operator)")
            s = s.Replace("§18.4", "[Pointer conversions](unsafe-code.md#pointer-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§18.3", "[Fixed and moveable variables](unsafe-code.md#fixed-and-moveable-variablesexpressions.md#addition-operator)")
            s = s.Replace("§18.2", "[Pointer types](unsafe-code.md#pointer-typesexpressions.md#addition-operator)")
            s = s.Replace("§18.1", "[Unsafe contexts](unsafe-code.md#unsafe-contextsexpressions.md#addition-operator)")
            s = s.Replace("§18", "[Unsafe code](unsafe-code.md#unsafe-codeexpressions.md#addition-operator)")
            s = s.Replace("§17.5.2.1", "[The IndexerName attribute](attributes.md#the-indexername-attributeexpressions.md#addition-operator)")
            s = s.Replace("§17.5.2", "[Interoperation with other .NET languages](attributes.md#interoperation-with-other-net-languagesexpressions.md#addition-operator)")
            s = s.Replace("§17.5.1", "[Interoperation with COM and Win32 components](attributes.md#interoperation-with-com-and-win32-componentsexpressions.md#addition-operator)")
            s = s.Replace("§17.5", "[Attributes for Interoperation](attributes.md#attributes-for-interoperationexpressions.md#addition-operator)")
            s = s.Replace("§17.4.4.3", "[The CallerMemberName attribute](attributes.md#the-callermembername-attributeexpressions.md#addition-operator)")
            s = s.Replace("§17.4.4.2", "[The CallerFilePath attribute](attributes.md#the-callerfilepath-attributeexpressions.md#addition-operator)")
            s = s.Replace("§17.4.4.1", "[The CallerLineNumber attribute](attributes.md#the-callerlinenumber-attributeexpressions.md#addition-operator)")
            s = s.Replace("§17.4.4", "[Caller info attributes](attributes.md#caller-info-attributesexpressions.md#addition-operator)")
            s = s.Replace("§17.4.3", "[The Obsolete attribute](attributes.md#the-obsolete-attributeexpressions.md#addition-operator)")
            s = s.Replace("§17.4.2.2", "[Conditional attribute classes](attributes.md#conditional-attribute-classesexpressions.md#addition-operator)")
            s = s.Replace("§17.4.2.1", "[Conditional methods](attributes.md#conditional-methodsexpressions.md#addition-operator)")
            s = s.Replace("§17.4.2", "[The Conditional attribute](attributes.md#the-conditional-attributeexpressions.md#addition-operator)")
            s = s.Replace("§17.4.1", "[The AttributeUsage attribute](attributes.md#the-attributeusage-attributeexpressions.md#addition-operator)")
            s = s.Replace("§17.4", "[Reserved attributes](attributes.md#reserved-attributesexpressions.md#addition-operator)")
            s = s.Replace("§17.3.2", "[Run-time retrieval of an attribute instance](attributes.md#run-time-retrieval-of-an-attribute-instanceexpressions.md#addition-operator)")
            s = s.Replace("§17.3.1", "[Compilation of an attribute](attributes.md#compilation-of-an-attributeexpressions.md#addition-operator)")
            s = s.Replace("§17.3", "[Attribute instances](attributes.md#attribute-instancesexpressions.md#addition-operator)")
            s = s.Replace("§17.2", "[Attribute specification](attributes.md#attribute-specificationexpressions.md#addition-operator)")
            s = s.Replace("§17.1.3", "[Attribute parameter types](attributes.md#attribute-parameter-typesexpressions.md#addition-operator)")
            s = s.Replace("§17.1.2", "[Positional and named parameters](attributes.md#positional-and-named-parametersexpressions.md#addition-operator)")
            s = s.Replace("§17.1.1", "[Attribute usage](attributes.md#attribute-usageexpressions.md#addition-operator)")
            s = s.Replace("§17.1", "[Attribute classes](attributes.md#attribute-classesexpressions.md#addition-operator)")
            s = s.Replace("§17", "[Attributes](attributes.md#attributesexpressions.md#addition-operator)")
            s = s.Replace("§16.4", "[Common Exception Classes](exceptions.md#common-exception-classesexpressions.md#addition-operator)")
            s = s.Replace("§16.3", "[How exceptions are handled](exceptions.md#how-exceptions-are-handledexpressions.md#addition-operator)")
            s = s.Replace("§16.2", "[The System.Exception class](exceptions.md#the-systemexception-classexpressions.md#addition-operator)")
            s = s.Replace("§16.1", "[Causes of exceptions](exceptions.md#causes-of-exceptionsexpressions.md#addition-operator)")
            s = s.Replace("§16", "[Exceptions](exceptions.md#exceptionsexpressions.md#addition-operator)")
            s = s.Replace("§15.4", "[Delegate invocation](delegates.md#delegate-invocationexpressions.md#addition-operator)")
            s = s.Replace("§15.3", "[Delegate instantiation](delegates.md#delegate-instantiationexpressions.md#addition-operator)")
            s = s.Replace("§15.2", "[Delegate compatibility](delegates.md#delegate-compatibilityexpressions.md#addition-operator)")
            s = s.Replace("§15.1", "[Delegate declarations](delegates.md#delegate-declarationsexpressions.md#addition-operator)")
            s = s.Replace("§15", "[Delegates](delegates.md#delegatesexpressions.md#addition-operator)")
            s = s.Replace("§14.5", "[Enum values and operations](enums.md#enum-values-and-operationsexpressions.md#addition-operator)")
            s = s.Replace("§14.4", "[The System.Enum type](enums.md#the-systemenum-typeexpressions.md#addition-operator)")
            s = s.Replace("§14.3", "[Enum members](enums.md#enum-membersexpressions.md#addition-operator)")
            s = s.Replace("§14.2", "[Enum modifiers](enums.md#enum-modifiersexpressions.md#addition-operator)")
            s = s.Replace("§14.1", "[Enum declarations](enums.md#enum-declarationsexpressions.md#addition-operator)")
            s = s.Replace("§14", "[Enums](enums.md#enumsexpressions.md#addition-operator)")
            s = s.Replace("§13.4.7", "[Abstract classes and interfaces](interfaces.md#abstract-classes-and-interfacesexpressions.md#addition-operator)")
            s = s.Replace("§13.4.6", "[Interface re-implementation](interfaces.md#interface-re-implementationexpressions.md#addition-operator)")
            s = s.Replace("§13.4.5", "[Interface implementation inheritance](interfaces.md#interface-implementation-inheritanceexpressions.md#addition-operator)")
            s = s.Replace("§13.4.4", "[Interface mapping](interfaces.md#interface-mappingexpressions.md#addition-operator)")
            s = s.Replace("§13.4.3", "[Implementation of generic methods](interfaces.md#implementation-of-generic-methodsexpressions.md#addition-operator)")
            s = s.Replace("§13.4.2", "[Uniqueness of implemented interfaces](interfaces.md#uniqueness-of-implemented-interfacesexpressions.md#addition-operator)")
            s = s.Replace("§13.4.1", "[Explicit interface member implementations](interfaces.md#explicit-interface-member-implementationsexpressions.md#addition-operator)")
            s = s.Replace("§13.4", "[Interface implementations](interfaces.md#interface-implementationsexpressions.md#addition-operator)")
            s = s.Replace("§13.3", "[Fully qualified interface member names](interfaces.md#fully-qualified-interface-member-namesexpressions.md#addition-operator)")
            s = s.Replace("§13.2.5", "[Interface member access](interfaces.md#interface-member-accessexpressions.md#addition-operator)")
            s = s.Replace("§13.2.4", "[Interface indexers](interfaces.md#interface-indexersexpressions.md#addition-operator)")
            s = s.Replace("§13.2.3", "[Interface events](interfaces.md#interface-eventsexpressions.md#addition-operator)")
            s = s.Replace("§13.2.2", "[Interface properties](interfaces.md#interface-propertiesexpressions.md#addition-operator)")
            s = s.Replace("§13.2.1", "[Interface methods](interfaces.md#interface-methodsexpressions.md#addition-operator)")
            s = s.Replace("§13.2", "[Interface members](interfaces.md#interface-membersexpressions.md#addition-operator)")
            s = s.Replace("§13.1.5", "[Interface body](interfaces.md#interface-bodyexpressions.md#addition-operator)")
            s = s.Replace("§13.1.4", "[Base interfaces](interfaces.md#base-interfacesexpressions.md#addition-operator)")
            s = s.Replace("§13.1.3.2", "[Variance conversion](interfaces.md#variance-conversionexpressions.md#addition-operator)")
            s = s.Replace("§13.1.3.1", "[Variance safety](interfaces.md#variance-safetyexpressions.md#addition-operator)")
            s = s.Replace("§13.1.3", "[Variant type parameter lists](interfaces.md#variant-type-parameter-listsexpressions.md#addition-operator)")
            s = s.Replace("§13.1.2", "[Partial modifier](interfaces.md#partial-modifierexpressions.md#addition-operator)")
            s = s.Replace("§13.1.1", "[Interface modifiers](interfaces.md#interface-modifiersexpressions.md#addition-operator)")
            s = s.Replace("§13.1", "[Interface declarations](interfaces.md#interface-declarationsexpressions.md#addition-operator)")
            s = s.Replace("§13", "[Interfaces](interfaces.md#interfacesexpressions.md#addition-operator)")
            s = s.Replace("§12.6", "[Array initializers](arrays.md#array-initializersexpressions.md#addition-operator)")
            s = s.Replace("§12.5", "[Array covariance](arrays.md#array-covarianceexpressions.md#addition-operator)")
            s = s.Replace("§12.4", "[Array members](arrays.md#array-membersexpressions.md#addition-operator)")
            s = s.Replace("§12.3", "[Array element access](arrays.md#array-element-accessexpressions.md#addition-operator)")
            s = s.Replace("§12.2", "[Array creation](arrays.md#array-creationexpressions.md#addition-operator)")
            s = s.Replace("§12.1.2", "[Arrays and the generic IList interface](arrays.md#arrays-and-the-generic-ilist-interfaceexpressions.md#addition-operator)")
            s = s.Replace("§12.1.1", "[The System.Array type](arrays.md#the-systemarray-typeexpressions.md#addition-operator)")
            s = s.Replace("§12.1", "[Array types](arrays.md#array-typesexpressions.md#addition-operator)")
            s = s.Replace("§12", "[Arrays](arrays.md#arraysexpressions.md#addition-operator)")
            s = s.Replace("§11.4.2", "[Database boolean type](structs.md#database-boolean-typeexpressions.md#addition-operator)")
            s = s.Replace("§11.4.1", "[Database integer type](structs.md#database-integer-typeexpressions.md#addition-operator)")
            s = s.Replace("§11.4", "[Struct examples](structs.md#struct-examplesexpressions.md#addition-operator)")
            s = s.Replace("§11.3.10", "[Static constructors](structs.md#static-constructorsexpressions.md#addition-operator)")
            s = s.Replace("§11.3.9", "[Destructors](structs.md#destructorsexpressions.md#addition-operator)")
            s = s.Replace("§11.3.8", "[Constructors](structs.md#constructorsexpressions.md#addition-operator)")
            s = s.Replace("§11.3.7", "[Field initializers](structs.md#field-initializersexpressions.md#addition-operator)")
            s = s.Replace("§11.3.6", "[Meaning of this](structs.md#meaning-of-thisexpressions.md#addition-operator)")
            s = s.Replace("§11.3.5", "[Boxing and unboxing](structs.md#boxing-and-unboxingexpressions.md#addition-operator)")
            s = s.Replace("§11.3.4", "[Default values](structs.md#default-valuesexpressions.md#addition-operator)")
            s = s.Replace("§11.3.3", "[Assignment](structs.md#assignmentexpressions.md#addition-operator)")
            s = s.Replace("§11.3.2", "[Inheritance](structs.md#inheritanceexpressions.md#addition-operator)")
            s = s.Replace("§11.3.1", "[Value semantics](structs.md#value-semanticsexpressions.md#addition-operator)")
            s = s.Replace("§11.3", "[Class and struct differences](structs.md#class-and-struct-differencesexpressions.md#addition-operator)")
            s = s.Replace("§11.2", "[Struct members](structs.md#struct-membersexpressions.md#addition-operator)")
            s = s.Replace("§11.1.4", "[Struct body](structs.md#struct-bodyexpressions.md#addition-operator)")
            s = s.Replace("§11.1.3", "[Struct interfaces](structs.md#struct-interfacesexpressions.md#addition-operator)")
            s = s.Replace("§11.1.2", "[Partial modifier](structs.md#partial-modifierexpressions.md#addition-operator)")
            s = s.Replace("§11.1.1", "[Struct modifiers](structs.md#struct-modifiersexpressions.md#addition-operator)")
            s = s.Replace("§11.1", "[Struct declarations](structs.md#struct-declarationsexpressions.md#addition-operator)")
            s = s.Replace("§11", "[Structs](structs.md#structsexpressions.md#addition-operator)")
            s = s.Replace("§10.15.2", "[Evaluation of a void-returning async function](classes.md#evaluation-of-a-void-returning-async-functionexpressions.md#addition-operator)")
            s = s.Replace("§10.15.1", "[Evaluation of a task-returning async function](classes.md#evaluation-of-a-task-returning-async-functionexpressions.md#addition-operator)")
            s = s.Replace("§10.15", "[Async Functions](classes.md#async-functionsexpressions.md#addition-operator)")
            s = s.Replace("§10.14.6", "[Implementation example](classes.md#implementation-exampleexpressions.md#addition-operator)")
            s = s.Replace("§10.14.5.1", "[The GetEnumerator method](classes.md#the-getenumerator-methodexpressions.md#addition-operator)")
            s = s.Replace("§10.14.5", "[Enumerable objects](classes.md#enumerable-objectsexpressions.md#addition-operator)")
            s = s.Replace("§10.14.4.3", "[The Dispose method](classes.md#the-dispose-methodexpressions.md#addition-operator)")
            s = s.Replace("§10.14.4.2", "[The Current property](classes.md#the-current-propertyexpressions.md#addition-operator)")
            s = s.Replace("§10.14.4.1", "[The MoveNext method](classes.md#the-movenext-methodexpressions.md#addition-operator)")
            s = s.Replace("§10.14.4", "[Enumerator objects](classes.md#enumerator-objectsexpressions.md#addition-operator)")
            s = s.Replace("§10.14.3", "[Yield type](classes.md#yield-typeexpressions.md#addition-operator)")
            s = s.Replace("§10.14.2", "[Enumerable interfaces](classes.md#enumerable-interfacesexpressions.md#addition-operator)")
            s = s.Replace("§10.14.1", "[Enumerator interfaces](classes.md#enumerator-interfacesexpressions.md#addition-operator)")
            s = s.Replace("§10.14", "[Iterators](classes.md#iteratorsexpressions.md#addition-operator)")
            s = s.Replace("§10.13", "[Destructors](classes.md#destructorsexpressions.md#addition-operator)")
            s = s.Replace("§10.12", "[Static constructors](classes.md#static-constructorsexpressions.md#addition-operator)")
            s = s.Replace("§10.11.6", "[Optional instance constructor parameters](classes.md#optional-instance-constructor-parametersexpressions.md#addition-operator)")
            s = s.Replace("§10.11.5", "[Private constructors](classes.md#private-constructorsexpressions.md#addition-operator)")
            s = s.Replace("§10.11.4", "[Default constructors](classes.md#default-constructorsexpressions.md#addition-operator)")
            s = s.Replace("§10.11.3", "[Constructor execution](classes.md#constructor-executionexpressions.md#addition-operator)")
            s = s.Replace("§10.11.2", "[Instance variable initializers](classes.md#instance-variable-initializersexpressions.md#addition-operator)")
            s = s.Replace("§10.11.1", "[Constructor initializers](classes.md#constructor-initializersexpressions.md#addition-operator)")
            s = s.Replace("§10.11", "[Instance constructors](classes.md#instance-constructorsexpressions.md#addition-operator)")
            s = s.Replace("§10.10.3", "[Conversion operators](classes.md#conversion-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§10.10.2", "[Binary operators](classes.md#binary-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§10.10.1", "[Unary operators](classes.md#unary-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§10.10", "[Operators](classes.md#operatorsexpressions.md#addition-operator)")
            s = s.Replace("§10.9.1", "[Indexer overloading](classes.md#indexer-overloadingexpressions.md#addition-operator)")
            s = s.Replace("§10.9", "[Indexers](classes.md#indexersexpressions.md#addition-operator)")
            s = s.Replace("§10.8.4", "[Virtual, sealed, override, and abstract event accessors](classes.md#virtual-sealed-override-and-abstract-event-accessorsexpressions.md#addition-operator)")
            s = s.Replace("§10.8.3", "[Static and instance events](classes.md#static-and-instance-eventsexpressions.md#addition-operator)")
            s = s.Replace("§10.8.2", "[Event accessors](classes.md#event-accessorsexpressions.md#addition-operator)")
            s = s.Replace("§10.8.1", "[Field-like events](classes.md#field-like-eventsexpressions.md#addition-operator)")
            s = s.Replace("§10.8", "[Events](classes.md#eventsexpressions.md#addition-operator)")
            s = s.Replace("§10.7.5", "[Virtual, sealed, override, and abstract property accessors](classes.md#virtual-sealed-override-and-abstract-property-accessorsexpressions.md#addition-operator)")
            s = s.Replace("§10.7.4", "[Accessibility](classes.md#accessibilityexpressions.md#addition-operator)")
            s = s.Replace("§10.7.3", "[Automatically implemented properties](classes.md#automatically-implemented-propertiesexpressions.md#addition-operator)")
            s = s.Replace("§10.7.2", "[Accessors](classes.md#accessorsexpressions.md#addition-operator)")
            s = s.Replace("§10.7.1", "[Static and instance properties](classes.md#static-and-instance-propertiesexpressions.md#addition-operator)")
            s = s.Replace("§10.7", "[Properties](classes.md#propertiesexpressions.md#addition-operator)")
            s = s.Replace("§10.6.11", "[Method overloading](classes.md#method-overloadingexpressions.md#addition-operator)")
            s = s.Replace("§10.6.10", "[Method body](classes.md#method-bodyexpressions.md#addition-operator)")
            s = s.Replace("§10.6.9", "[Extension methods](classes.md#extension-methodsexpressions.md#addition-operator)")
            s = s.Replace("§10.6.8", "[Partial methods (recap)](classes.md#partial-methods-recapexpressions.md#addition-operator)")
            s = s.Replace("§10.6.7", "[External methods](classes.md#external-methodsexpressions.md#addition-operator)")
            s = s.Replace("§10.6.6", "[Abstract methods](classes.md#abstract-methodsexpressions.md#addition-operator)")
            s = s.Replace("§10.6.5", "[Sealed methods](classes.md#sealed-methodsexpressions.md#addition-operator)")
            s = s.Replace("§10.6.4", "[Override methods](classes.md#override-methodsexpressions.md#addition-operator)")
            s = s.Replace("§10.6.3", "[Virtual methods](classes.md#virtual-methodsexpressions.md#addition-operator)")
            s = s.Replace("§10.6.2", "[Static and instance methods](classes.md#static-and-instance-methodsexpressions.md#addition-operator)")
            s = s.Replace("§10.6.1.4", "[Parameter arrays](classes.md#parameter-arraysexpressions.md#addition-operator)")
            s = s.Replace("§10.6.1.3", "[Output parameters](classes.md#output-parametersexpressions.md#addition-operator)")
            s = s.Replace("§10.6.1.2", "[Reference parameters](classes.md#reference-parametersexpressions.md#addition-operator)")
            s = s.Replace("§10.6.1.1", "[Value parameters](classes.md#value-parametersexpressions.md#addition-operator)")
            s = s.Replace("§10.6.1", "[Method parameters](classes.md#method-parametersexpressions.md#addition-operator)")
            s = s.Replace("§10.6", "[Methods](classes.md#methodsexpressions.md#addition-operator)")
            s = s.Replace("§10.5.5.2", "[Instance field initialization](classes.md#instance-field-initializationexpressions.md#addition-operator)")
            s = s.Replace("§10.5.5.1", "[Static field initialization](classes.md#static-field-initializationexpressions.md#addition-operator)")
            s = s.Replace("§10.5.5", "[Variable initializers](classes.md#variable-initializersexpressions.md#addition-operator)")
            s = s.Replace("§10.5.4", "[Field initialization](classes.md#field-initializationexpressions.md#addition-operator)")
            s = s.Replace("§10.5.3", "[Volatile fields](classes.md#volatile-fieldsexpressions.md#addition-operator)")
            s = s.Replace("§10.5.2.2", "[Versioning of constants and static readonly fields](classes.md#versioning-of-constants-and-static-readonly-fieldsexpressions.md#addition-operator)")
            s = s.Replace("§10.5.2.1", "[Using static readonly fields for constants](classes.md#using-static-readonly-fields-for-constantsexpressions.md#addition-operator)")
            s = s.Replace("§10.5.2", "[Readonly fields](classes.md#readonly-fieldsexpressions.md#addition-operator)")
            s = s.Replace("§10.5.1", "[Static and instance fields](classes.md#static-and-instance-fieldsexpressions.md#addition-operator)")
            s = s.Replace("§10.5", "[Fields](classes.md#fieldsexpressions.md#addition-operator)")
            s = s.Replace("§10.4", "[Constants](classes.md#constantsexpressions.md#addition-operator)")
            s = s.Replace("§10.3.9.4", "[Member names reserved for destructors](classes.md#member-names-reserved-for-destructorsexpressions.md#addition-operator)")
            s = s.Replace("§10.3.9.3", "[Member names reserved for indexers](classes.md#member-names-reserved-for-indexersexpressions.md#addition-operator)")
            s = s.Replace("§10.3.9.2", "[Member names reserved for events](classes.md#member-names-reserved-for-eventsexpressions.md#addition-operator)")
            s = s.Replace("§10.3.9.1", "[Member names reserved for properties](classes.md#member-names-reserved-for-propertiesexpressions.md#addition-operator)")
            s = s.Replace("§10.3.9", "[Reserved member names](classes.md#reserved-member-namesexpressions.md#addition-operator)")
            s = s.Replace("§10.3.8.6", "[Nested types in generic classes](classes.md#nested-types-in-generic-classesexpressions.md#addition-operator)")
            s = s.Replace("§10.3.8.5", "[Access to private and protected members of the containing type](classes.md#access-to-private-and-protected-members-of-the-containing-typeexpressions.md#addition-operator)")
            s = s.Replace("§10.3.8.4", "[this access](classes.md#this-accessexpressions.md#addition-operator)")
            s = s.Replace("§10.3.8.3", "[Hiding](classes.md#hidingexpressions.md#addition-operator)")
            s = s.Replace("§10.3.8.2", "[Declared accessibility](classes.md#declared-accessibilityexpressions.md#addition-operator)")
            s = s.Replace("§10.3.8.1", "[Fully qualified name](classes.md#fully-qualified-nameexpressions.md#addition-operator)")
            s = s.Replace("§10.3.8", "[Nested types](classes.md#nested-typesexpressions.md#addition-operator)")
            s = s.Replace("§10.3.7", "[Static and instance members](classes.md#static-and-instance-membersexpressions.md#addition-operator)")
            s = s.Replace("§10.3.6", "[Constituent types](classes.md#constituent-typesexpressions.md#addition-operator)")
            s = s.Replace("§10.3.5", "[Access modifiers](classes.md#access-modifiersexpressions.md#addition-operator)")
            s = s.Replace("§10.3.4", "[The new modifier](classes.md#the-new-modifierexpressions.md#addition-operator)")
            s = s.Replace("§10.3.3", "[Inheritance](classes.md#inheritanceexpressions.md#addition-operator)")
            s = s.Replace("§10.3.2", "[Members of constructed types](classes.md#members-of-constructed-typesexpressions.md#addition-operator)")
            s = s.Replace("§10.3.1", "[The instance type](classes.md#the-instance-typeexpressions.md#addition-operator)")
            s = s.Replace("§10.3", "[Class members](classes.md#class-membersexpressions.md#addition-operator)")
            s = s.Replace("§10.2.8", "[Name binding](classes.md#name-bindingexpressions.md#addition-operator)")
            s = s.Replace("§10.2.7", "[Partial methods](classes.md#partial-methodsexpressions.md#addition-operator)")
            s = s.Replace("§10.2.6", "[Members](classes.md#membersexpressions.md#addition-operator)")
            s = s.Replace("§10.2.5", "[Base interfaces](classes.md#base-interfacesexpressions.md#addition-operator)")
            s = s.Replace("§10.2.4", "[Base class](classes.md#base-classexpressions.md#addition-operator)")
            s = s.Replace("§10.2.3", "[Type parameters and constraints](classes.md#type-parameters-and-constraintsexpressions.md#addition-operator)")
            s = s.Replace("§10.2.2", "[Modifiers](classes.md#modifiersexpressions.md#addition-operator)")
            s = s.Replace("§10.2.1", "[Attributes](classes.md#attributesexpressions.md#addition-operator)")
            s = s.Replace("§10.2", "[Partial types](classes.md#partial-typesexpressions.md#addition-operator)")
            s = s.Replace("§10.1.6", "[Class body](classes.md#class-bodyexpressions.md#addition-operator)")
            s = s.Replace("§10.1.5", "[Type parameter constraints](classes.md#type-parameter-constraintsexpressions.md#addition-operator)")
            s = s.Replace("§10.1.4.2", "[Interface implementations](classes.md#interface-implementationsexpressions.md#addition-operator)")
            s = s.Replace("§10.1.4.1", "[Base classes](classes.md#base-classesexpressions.md#addition-operator)")
            s = s.Replace("§10.1.4", "[Class base specification](classes.md#class-base-specificationexpressions.md#addition-operator)")
            s = s.Replace("§10.1.3", "[Type parameters](classes.md#type-parametersexpressions.md#addition-operator)")
            s = s.Replace("§10.1.2", "[Partial modifier](classes.md#partial-modifierexpressions.md#addition-operator)")
            s = s.Replace("§10.1.1.3.1", "[Referencing static class types](classes.md#referencing-static-class-typesexpressions.md#addition-operator)")
            s = s.Replace("§10.1.1.3", "[Static classes](classes.md#static-classesexpressions.md#addition-operator)")
            s = s.Replace("§10.1.1.2", "[Sealed classes](classes.md#sealed-classesexpressions.md#addition-operator)")
            s = s.Replace("§10.1.1.1", "[Abstract classes](classes.md#abstract-classesexpressions.md#addition-operator)")
            s = s.Replace("§10.1.1", "[Class modifiers](classes.md#class-modifiersexpressions.md#addition-operator)")
            s = s.Replace("§10.1", "[Class declarations](classes.md#class-declarationsexpressions.md#addition-operator)")
            s = s.Replace("§10", "[Classes](classes.md#classesexpressions.md#addition-operator)")
            s = s.Replace("§9.7.1", "[Uniqueness of aliases](namespaces.md#uniqueness-of-aliasesexpressions.md#addition-operator)")
            s = s.Replace("§9.7", "[Namespace alias qualifiers](namespaces.md#namespace-alias-qualifiersexpressions.md#addition-operator)")
            s = s.Replace("§9.6", "[Type declarations](namespaces.md#type-declarationsexpressions.md#addition-operator)")
            s = s.Replace("§9.5", "[Namespace members](namespaces.md#namespace-membersexpressions.md#addition-operator)")
            s = s.Replace("§9.4.2", "[Using namespace directives](namespaces.md#using-namespace-directivesexpressions.md#addition-operator)")
            s = s.Replace("§9.4.1", "[Using alias directives](namespaces.md#using-alias-directivesexpressions.md#addition-operator)")
            s = s.Replace("§9.4", "[Using directives](namespaces.md#using-directivesexpressions.md#addition-operator)")
            s = s.Replace("§9.3", "[Extern aliases](namespaces.md#extern-aliasesexpressions.md#addition-operator)")
            s = s.Replace("§9.2", "[Namespace declarations](namespaces.md#namespace-declarationsexpressions.md#addition-operator)")
            s = s.Replace("§9.1", "[Compilation units](namespaces.md#compilation-unitsexpressions.md#addition-operator)")
            s = s.Replace("§9", "[Namespaces](namespaces.md#namespacesexpressions.md#addition-operator)")
            s = s.Replace("§8.14", "[The yield statement](statements.md#the-yield-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.13", "[The using statement](statements.md#the-using-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.12", "[The lock statement](statements.md#the-lock-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.11", "[The checked and unchecked statements](statements.md#the-checked-and-unchecked-statementsexpressions.md#addition-operator)")
            s = s.Replace("§8.10", "[The try statement](statements.md#the-try-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.9.5", "[The throw statement](statements.md#the-throw-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.9.4", "[The return statement](statements.md#the-return-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.9.3", "[The goto statement](statements.md#the-goto-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.9.2", "[The continue statement](statements.md#the-continue-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.9.1", "[The break statement](statements.md#the-break-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.9", "[Jump statements](statements.md#jump-statementsexpressions.md#addition-operator)")
            s = s.Replace("§8.8.4", "[The foreach statement](statements.md#the-foreach-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.8.3", "[The for statement](statements.md#the-for-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.8.2", "[The do statement](statements.md#the-do-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.8.1", "[The while statement](statements.md#the-while-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.8", "[Iteration statements](statements.md#iteration-statementsexpressions.md#addition-operator)")
            s = s.Replace("§8.7.2", "[The switch statement](statements.md#the-switch-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.7.1", "[The if statement](statements.md#the-if-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.7", "[Selection statements](statements.md#selection-statementsexpressions.md#addition-operator)")
            s = s.Replace("§8.6", "[Expression statements](statements.md#expression-statementsexpressions.md#addition-operator)")
            s = s.Replace("§8.5.2", "[Local constant declarations](statements.md#local-constant-declarationsexpressions.md#addition-operator)")
            s = s.Replace("§8.5.1", "[Local variable declarations](statements.md#local-variable-declarationsexpressions.md#addition-operator)")
            s = s.Replace("§8.5", "[Declaration statements](statements.md#declaration-statementsexpressions.md#addition-operator)")
            s = s.Replace("§8.4", "[Labeled statements](statements.md#labeled-statementsexpressions.md#addition-operator)")
            s = s.Replace("§8.3", "[The empty statement](statements.md#the-empty-statementexpressions.md#addition-operator)")
            s = s.Replace("§8.2.1", "[Statement lists](statements.md#statement-listsexpressions.md#addition-operator)")
            s = s.Replace("§8.2", "[Blocks](statements.md#blocksexpressions.md#addition-operator)")
            s = s.Replace("§8.1", "[End points and reachability](statements.md#end-points-and-reachabilityexpressions.md#addition-operator)")
            s = s.Replace("§8", "[Statements](statements.md#statementsexpressions.md#addition-operator)")
            s = s.Replace("§7.20", "[Boolean expressions](expressions.md#boolean-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.19", "[Constant expressions](expressions.md#constant-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.18", "[Expression](expressions.md#expressionexpressions.md#addition-operator)")
            s = s.Replace("§7.17.3", "[Event assignment](expressions.md#event-assignmentexpressions.md#addition-operator)")
            s = s.Replace("§7.17.2", "[Compound assignment](expressions.md#compound-assignmentexpressions.md#addition-operator)")
            s = s.Replace("§7.17.1", "[Simple assignment](expressions.md#simple-assignmentexpressions.md#addition-operator)")
            s = s.Replace("§7.17", "[Assignment operators](expressions.md#assignment-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.16.3", "[The query expression pattern](expressions.md#the-query-expression-patternexpressions.md#addition-operator)")
            s = s.Replace("§7.16.2.7", "[Transparent identifiers](expressions.md#transparent-identifiersexpressions.md#addition-operator)")
            s = s.Replace("§7.16.2.6", "[Groupby clauses](expressions.md#groupby-clausesexpressions.md#addition-operator)")
            s = s.Replace("§7.16.2.5", "[Select clauses](expressions.md#select-clausesexpressions.md#addition-operator)")
            s = s.Replace("§7.16.2.4", "[From, let, where, join and orderby clauses](expressions.md#from-let-where-join-and-orderby-clausesexpressions.md#addition-operator)")
            s = s.Replace("§7.16.2.3", "[Degenerate query expressions](expressions.md#degenerate-query-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.16.2.2", "[Explicit range variable types](expressions.md#explicit-range-variable-typesexpressions.md#addition-operator)")
            s = s.Replace("§7.16.2.1", "[Select and groupby clauses with continuations](expressions.md#select-and-groupby-clauses-with-continuationsexpressions.md#addition-operator)")
            s = s.Replace("§7.16.2", "[Query expression translation](expressions.md#query-expression-translationexpressions.md#addition-operator)")
            s = s.Replace("§7.16.1", "[Ambiguities in query expressions](expressions.md#ambiguities-in-query-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.16", "[Query expressions](expressions.md#query-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.15.6", "[Evaluation of anonymous function expressions](expressions.md#evaluation-of-anonymous-function-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.15.5.2", "[Instantiation of local variables](expressions.md#instantiation-of-local-variablesexpressions.md#addition-operator)")
            s = s.Replace("§7.15.5.1", "[Captured outer variables](expressions.md#captured-outer-variablesexpressions.md#addition-operator)")
            s = s.Replace("§7.15.5", "[Outer variables](expressions.md#outer-variablesexpressions.md#addition-operator)")
            s = s.Replace("§7.15.4", "[Anonymous functions and dynamic binding](expressions.md#anonymous-functions-and-dynamic-bindingexpressions.md#addition-operator)")
            s = s.Replace("§7.15.3", "[Overload resolution and anonymous functions](expressions.md#overload-resolution-and-anonymous-functionsexpressions.md#addition-operator)")
            s = s.Replace("§7.15.2", "[Anonymous function bodies](expressions.md#anonymous-function-bodiesexpressions.md#addition-operator)")
            s = s.Replace("§7.15.1", "[Anonymous function signatures](expressions.md#anonymous-function-signaturesexpressions.md#addition-operator)")
            s = s.Replace("§7.15", "[Anonymous function expressions](expressions.md#anonymous-function-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.14", "[Conditional operator](expressions.md#conditional-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.13", "[The null coalescing operator](expressions.md#the-null-coalescing-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.12.2", "[User-defined conditional logical operators](expressions.md#user-defined-conditional-logical-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.12.1", "[Boolean conditional logical operators](expressions.md#boolean-conditional-logical-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.12", "[Conditional logical operators](expressions.md#conditional-logical-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.11.4", "[Nullable boolean logical operators](expressions.md#nullable-boolean-logical-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.11.3", "[Boolean logical operators](expressions.md#boolean-logical-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.11.2", "[Enumeration logical operators](expressions.md#enumeration-logical-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.11.1", "[Integer logical operators](expressions.md#integer-logical-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.11", "[Logical operators](expressions.md#logical-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.10.11", "[The as operator](expressions.md#the-as-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.10.10", "[The is operator](expressions.md#the-is-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.10.9", "[Equality operators and null](expressions.md#equality-operators-and-nullexpressions.md#addition-operator)")
            s = s.Replace("§7.10.8", "[Delegate equality operators](expressions.md#delegate-equality-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.10.7", "[String equality operators](expressions.md#string-equality-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.10.6", "[Reference type equality operators](expressions.md#reference-type-equality-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.10.5", "[Enumeration comparison operators](expressions.md#enumeration-comparison-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.10.4", "[Boolean equality operators](expressions.md#boolean-equality-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.10.3", "[Decimal comparison operators](expressions.md#decimal-comparison-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.10.2", "[Floating-point comparison operators](expressions.md#floating-point-comparison-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.10.1", "[Integer comparison operators](expressions.md#integer-comparison-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.10", "[Relational and type-testing operators](expressions.md#relational-and-type-testing-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.9", "[Shift operators](expressions.md#shift-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.8.5", "[Subtraction operator](expressions.md#subtraction-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.8.4", "[Addition operator](expressions.md#addition-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.8.3", "[Remainder operator](expressions.md#remainder-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.8.2", "[Division operator](expressions.md#division-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.8.1", "[Multiplication operator](expressions.md#multiplication-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.8", "[Arithmetic operators](expressions.md#arithmetic-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.7.7.3", "[Runtime evaluation of await expressions](expressions.md#runtime-evaluation-of-await-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.7.7.2", "[Classification of await expressions](expressions.md#classification-of-await-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.7.7.1", "[Awaitable expressions](expressions.md#awaitable-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.7.7", "[Await expressions](expressions.md#await-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.7.6", "[Cast expressions](expressions.md#cast-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.7.5", "[Prefix increment and decrement operators](expressions.md#prefix-increment-and-decrement-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.7.4", "[Bitwise complement operator](expressions.md#bitwise-complement-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.7.3", "[Logical negation operator](expressions.md#logical-negation-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.7.2", "[Unary minus operator](expressions.md#unary-minus-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.7.1", "[Unary plus operator](expressions.md#unary-plus-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.7", "[Unary operators](expressions.md#unary-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.14", "[Anonymous method expressions](expressions.md#anonymous-method-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.13", "[Default value expressions](expressions.md#default-value-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.12", "[The checked and unchecked operators](expressions.md#the-checked-and-unchecked-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.11", "[The typeof operator](expressions.md#the-typeof-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.6.10.6", "[Anonymous object creation expressions](expressions.md#anonymous-object-creation-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.10.5", "[Delegate creation expressions](expressions.md#delegate-creation-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.10.4", "[Array creation expressions](expressions.md#array-creation-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.10.3", "[Collection initializers](expressions.md#collection-initializersexpressions.md#addition-operator)")
            s = s.Replace("§7.6.10.2", "[Object initializers](expressions.md#object-initializersexpressions.md#addition-operator)")
            s = s.Replace("§7.6.10.1", "[Object creation expressions](expressions.md#object-creation-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.10", "[The new operator](expressions.md#the-new-operatorexpressions.md#addition-operator)")
            s = s.Replace("§7.6.9", "[Postfix increment and decrement operators](expressions.md#postfix-increment-and-decrement-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.8", "[Base access](expressions.md#base-accessexpressions.md#addition-operator)")
            s = s.Replace("§7.6.7", "[This access](expressions.md#this-accessexpressions.md#addition-operator)")
            s = s.Replace("§7.6.6.2", "[Indexer access](expressions.md#indexer-accessexpressions.md#addition-operator)")
            s = s.Replace("§7.6.6.1", "[Array access](expressions.md#array-accessexpressions.md#addition-operator)")
            s = s.Replace("§7.6.6", "[Element access](expressions.md#element-accessexpressions.md#addition-operator)")
            s = s.Replace("§7.6.5.3", "[Delegate invocations](expressions.md#delegate-invocationsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.5.2", "[Extension method invocations](expressions.md#extension-method-invocationsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.5.1", "[Method invocations](expressions.md#method-invocationsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.5", "[Invocation expressions](expressions.md#invocation-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.4.2", "[Grammar ambiguities](expressions.md#grammar-ambiguitiesexpressions.md#addition-operator)")
            s = s.Replace("§7.6.4.1", "[Identical simple names and type names](expressions.md#identical-simple-names-and-type-namesexpressions.md#addition-operator)")
            s = s.Replace("§7.6.4", "[Member access](expressions.md#member-accessexpressions.md#addition-operator)")
            s = s.Replace("§7.6.3", "[Parenthesized expressions](expressions.md#parenthesized-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.6.2.1", "[Invariant meaning in blocks](expressions.md#invariant-meaning-in-blocksexpressions.md#addition-operator)")
            s = s.Replace("§7.6.2", "[Simple names](expressions.md#simple-namesexpressions.md#addition-operator)")
            s = s.Replace("§7.6.1", "[Literals](expressions.md#literalsexpressions.md#addition-operator)")
            s = s.Replace("§7.6", "[Primary expressions](expressions.md#primary-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.5.5.1", "[Invocations on boxed instances](expressions.md#invocations-on-boxed-instancesexpressions.md#addition-operator)")
            s = s.Replace("§7.5.5", "[Function member invocation](expressions.md#function-member-invocationexpressions.md#addition-operator)")
            s = s.Replace("§7.5.4", "[Compile-time checking of dynamic overload resolution](expressions.md#compile-time-checking-of-dynamic-overload-resolutionexpressions.md#addition-operator)")
            s = s.Replace("§7.5.3.6", "[Overloading in generic classes](expressions.md#overloading-in-generic-classesexpressions.md#addition-operator)")
            s = s.Replace("§7.5.3.5", "[Better conversion target](expressions.md#better-conversion-targetexpressions.md#addition-operator)")
            s = s.Replace("§7.5.3.4", "[Better conversion from type](expressions.md#better-conversion-from-typeexpressions.md#addition-operator)")
            s = s.Replace("§7.5.3.3", "[Better conversion from expression](expressions.md#better-conversion-from-expressionexpressions.md#addition-operator)")
            s = s.Replace("§7.5.3.2", "[Better function member](expressions.md#better-function-memberexpressions.md#addition-operator)")
            s = s.Replace("§7.5.3.1", "[Applicable function member](expressions.md#applicable-function-memberexpressions.md#addition-operator)")
            s = s.Replace("§7.5.3", "[Overload resolution](expressions.md#overload-resolutionexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.14", "[Finding the best common type of a set of expressions](expressions.md#finding-the-best-common-type-of-a-set-of-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.13", "[Type inference for conversion of method groups](expressions.md#type-inference-for-conversion-of-method-groupsexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.12", "[Inferred return type](expressions.md#inferred-return-typeexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.11", "[Fixing](expressions.md#fixingexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.10", "[Upper-bound inferences](expressions.md#upper-bound-inferencesexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.9", "[Lower-bound inferences](expressions.md#lower-bound-inferencesexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.8", "[Exact inferences](expressions.md#exact-inferencesexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.7", "[Explicit parameter type inferences](expressions.md#explicit-parameter-type-inferencesexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.6", "[Output type inferences](expressions.md#output-type-inferencesexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.5", "[Dependence](expressions.md#dependenceexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.4", "[Output types](expressions.md#output-typesexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.3", "[Input types](expressions.md#input-typesexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.2", "[The second phase](expressions.md#the-second-phaseexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2.1", "[The first phase](expressions.md#the-first-phaseexpressions.md#addition-operator)")
            s = s.Replace("§7.5.2", "[Type inference](expressions.md#type-inferenceexpressions.md#addition-operator)")
            s = s.Replace("§7.5.1.2", "[Run-time evaluation of argument lists](expressions.md#run-time-evaluation-of-argument-listsexpressions.md#addition-operator)")
            s = s.Replace("§7.5.1.1", "[Corresponding parameters](expressions.md#corresponding-parametersexpressions.md#addition-operator)")
            s = s.Replace("§7.5.1", "[Argument lists](expressions.md#argument-listsexpressions.md#addition-operator)")
            s = s.Replace("§7.5", "[Function members](expressions.md#function-membersexpressions.md#addition-operator)")
            s = s.Replace("§7.4.1", "[Base types](expressions.md#base-typesexpressions.md#addition-operator)")
            s = s.Replace("§7.4", "[Member lookup](expressions.md#member-lookupexpressions.md#addition-operator)")
            s = s.Replace("§7.3.7", "[Lifted operators](expressions.md#lifted-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.3.6.2", "[Binary numeric promotions](expressions.md#binary-numeric-promotionsexpressions.md#addition-operator)")
            s = s.Replace("§7.3.6.1", "[Unary numeric promotions](expressions.md#unary-numeric-promotionsexpressions.md#addition-operator)")
            s = s.Replace("§7.3.6", "[Numeric promotions](expressions.md#numeric-promotionsexpressions.md#addition-operator)")
            s = s.Replace("§7.3.5", "[Candidate user-defined operators](expressions.md#candidate-user-defined-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.3.4", "[Binary operator overload resolution](expressions.md#binary-operator-overload-resolutionexpressions.md#addition-operator)")
            s = s.Replace("§7.3.3", "[Unary operator overload resolution](expressions.md#unary-operator-overload-resolutionexpressions.md#addition-operator)")
            s = s.Replace("§7.3.2", "[Operator overloading](expressions.md#operator-overloadingexpressions.md#addition-operator)")
            s = s.Replace("§7.3.1", "[Operator precedence and associativity](expressions.md#operator-precedence-and-associativityexpressions.md#addition-operator)")
            s = s.Replace("§7.3", "[Operators](expressions.md#operatorsexpressions.md#addition-operator)")
            s = s.Replace("§7.2.3", "[Types of constituent expressions](expressions.md#types-of-constituent-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.2.2", "[Dynamic binding](expressions.md#dynamic-bindingexpressions.md#addition-operator)")
            s = s.Replace("§7.2.1", "[Binding-time](expressions.md#binding-timeexpressions.md#addition-operator)")
            s = s.Replace("§7.2", "[Static and Dynamic Binding](expressions.md#static-and-dynamic-bindingexpressions.md#addition-operator)")
            s = s.Replace("§7.1.1", "[Values of expressions](expressions.md#values-of-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§7.1", "[Expression classifications](expressions.md#expression-classificationsexpressions.md#addition-operator)")
            s = s.Replace("§7", "[Expressions](expressions.md#expressionsexpressions.md#addition-operator)")
            s = s.Replace("§6.6", "[Method group conversions](conversions.md#method-group-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.5.3", "[Implementation example](conversions.md#implementation-exampleexpressions.md#addition-operator)")
            s = s.Replace("§6.5.2", "[Evaluation of anonymous function conversions to expression tree types](conversions.md#evaluation-of-anonymous-function-conversions-to-expression-tree-typesexpressions.md#addition-operator)")
            s = s.Replace("§6.5.1", "[Evaluation of anonymous function conversions to delegate types](conversions.md#evaluation-of-anonymous-function-conversions-to-delegate-typesexpressions.md#addition-operator)")
            s = s.Replace("§6.5", "[Anonymous function conversions](conversions.md#anonymous-function-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.4.5", "[Processing of user-defined explicit conversions](conversions.md#processing-of-user-defined-explicit-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.4.4", "[Processing of user-defined implicit conversions](conversions.md#processing-of-user-defined-implicit-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.4.3", "[Evaluation of user-defined conversions](conversions.md#evaluation-of-user-defined-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.4.2", "[Lifted conversion operators](conversions.md#lifted-conversion-operatorsexpressions.md#addition-operator)")
            s = s.Replace("§6.4.1", "[Permitted user-defined conversions](conversions.md#permitted-user-defined-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.4", "[User-defined conversions](conversions.md#user-defined-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.3.2", "[Standard explicit conversions](conversions.md#standard-explicit-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.3.1", "[Standard implicit conversions](conversions.md#standard-implicit-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.3", "[Standard conversions](conversions.md#standard-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.2.8", "[User-defined explicit conversions](conversions.md#user-defined-explicit-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.2.7", "[Explicit conversions involving type parameters](conversions.md#explicit-conversions-involving-type-parametersexpressions.md#addition-operator)")
            s = s.Replace("§6.2.6", "[Explicit dynamic conversions](conversions.md#explicit-dynamic-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.2.5", "[Unboxing conversions](conversions.md#unboxing-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.2.4", "[Explicit reference conversions](conversions.md#explicit-reference-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.2.3", "[Explicit nullable conversions](conversions.md#explicit-nullable-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.2.2", "[Explicit enumeration conversions](conversions.md#explicit-enumeration-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.2.1", "[Explicit numeric conversions](conversions.md#explicit-numeric-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.2", "[Explicit conversions](conversions.md#explicit-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.1.12", "[Anonymous function conversions and method group conversions](conversions.md#anonymous-function-conversions-and-method-group-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.1.11", "[User-defined implicit conversions](conversions.md#user-defined-implicit-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.1.10", "[Implicit conversions involving type parameters](conversions.md#implicit-conversions-involving-type-parametersexpressions.md#addition-operator)")
            s = s.Replace("§6.1.9", "[Implicit constant expression conversions](conversions.md#implicit-constant-expression-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.1.8", "[Implicit dynamic conversions](conversions.md#implicit-dynamic-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.1.7", "[Boxing conversions](conversions.md#boxing-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.1.6", "[Implicit reference conversions](conversions.md#implicit-reference-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.1.5", "[Null literal conversions](conversions.md#null-literal-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.1.4", "[Implicit nullable conversions](conversions.md#implicit-nullable-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.1.3", "[Implicit enumeration conversions](conversions.md#implicit-enumeration-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.1.2", "[Implicit numeric conversions](conversions.md#implicit-numeric-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6.1.1", "[Identity conversion](conversions.md#identity-conversionexpressions.md#addition-operator)")
            s = s.Replace("§6.1", "[Implicit conversions](conversions.md#implicit-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§6", "[Conversions](conversions.md#conversionsexpressions.md#addition-operator)")
            s = s.Replace("§5.5", "[Atomicity of variable references](variables.md#atomicity-of-variable-referencesexpressions.md#addition-operator)")
            s = s.Replace("§5.4", "[Variable references](variables.md#variable-referencesexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.29", "[Anonymous functions](variables.md#anonymous-functionsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.28", "[?: (conditional) expressions](variables.md#-conditional-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.27", "[?? (null coalescing) expressions](variables.md#-null-coalescing-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.26", "[! (logical negation) expressions](variables.md#-logical-negation-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.25", "[|| (conditional OR) expressions](variables.md#-conditional-or-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.24", "[&& (conditional AND) expressions](variables.md#-conditional-and-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.23", "[Simple assignment expressions](variables.md#simple-assignment-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.22", "[Invocation expressions and object creation expressions](variables.md#invocation-expressions-and-object-creation-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.21", "[General rules for expressions with embedded expressions](variables.md#general-rules-for-expressions-with-embedded-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.20", "[General rules for simple expressions](variables.md#general-rules-for-simple-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.19", "[Yield statements](variables.md#yield-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.18", "[Lock statements](variables.md#lock-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.17", "[Using statements](variables.md#using-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.16", "[Foreach statements](variables.md#foreach-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.15", "[Try-catch-finally statements](variables.md#try-catch-finally-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.14", "[Try-finally statements](variables.md#try-finally-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.13", "[Try-catch statements](variables.md#try-catch-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.12", "[Return statements](variables.md#return-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.11", "[Throw statements](variables.md#throw-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.10", "[Break, continue, and goto statements](variables.md#break-continue-and-goto-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.9", "[For statements](variables.md#for-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.8", "[Do statements](variables.md#do-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.7", "[While statements](variables.md#while-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.6", "[Switch statements](variables.md#switch-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.5", "[If statements](variables.md#if-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.4", "[Declaration statements](variables.md#declaration-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.3", "[Expression statements](variables.md#expression-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.2", "[Block statements, checked, and unchecked statements](variables.md#block-statements-checked-and-unchecked-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3.1", "[General rules for statements](variables.md#general-rules-for-statementsexpressions.md#addition-operator)")
            s = s.Replace("§5.3.3", "[Precise rules for determining definite assignment](variables.md#precise-rules-for-determining-definite-assignmentexpressions.md#addition-operator)")
            s = s.Replace("§5.3.2", "[Initially unassigned variables](variables.md#initially-unassigned-variablesexpressions.md#addition-operator)")
            s = s.Replace("§5.3.1", "[Initially assigned variables](variables.md#initially-assigned-variablesexpressions.md#addition-operator)")
            s = s.Replace("§5.3", "[Definite assignment](variables.md#definite-assignmentexpressions.md#addition-operator)")
            s = s.Replace("§5.2", "[Default values](variables.md#default-valuesexpressions.md#addition-operator)")
            s = s.Replace("§5.1.7", "[Local variables](variables.md#local-variablesexpressions.md#addition-operator)")
            s = s.Replace("§5.1.6", "[Output parameters](variables.md#output-parametersexpressions.md#addition-operator)")
            s = s.Replace("§5.1.5", "[Reference parameters](variables.md#reference-parametersexpressions.md#addition-operator)")
            s = s.Replace("§5.1.4", "[Value parameters](variables.md#value-parametersexpressions.md#addition-operator)")
            s = s.Replace("§5.1.3", "[Array elements](variables.md#array-elementsexpressions.md#addition-operator)")
            s = s.Replace("§5.1.2.2", "[Instance variables in structs](variables.md#instance-variables-in-structsexpressions.md#addition-operator)")
            s = s.Replace("§5.1.2.1", "[Instance variables in classes](variables.md#instance-variables-in-classesexpressions.md#addition-operator)")
            s = s.Replace("§5.1.2", "[Instance variables](variables.md#instance-variablesexpressions.md#addition-operator)")
            s = s.Replace("§5.1.1", "[Static variables](variables.md#static-variablesexpressions.md#addition-operator)")
            s = s.Replace("§5.1", "[Variable categories](variables.md#variable-categoriesexpressions.md#addition-operator)")
            s = s.Replace("§5", "[Variables](variables.md#variablesexpressions.md#addition-operator)")
            s = s.Replace("§4.6", "[Expression tree types](types.md#expression-tree-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.5", "[Type parameters](types.md#type-parametersexpressions.md#addition-operator)")
            s = s.Replace("§4.4.4", "[Satisfying constraints](types.md#satisfying-constraintsexpressions.md#addition-operator)")
            s = s.Replace("§4.4.3", "[Bound and unbound types](types.md#bound-and-unbound-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.4.2", "[Open and closed types](types.md#open-and-closed-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.4.1", "[Type arguments](types.md#type-argumentsexpressions.md#addition-operator)")
            s = s.Replace("§4.4", "[Constructed types](types.md#constructed-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.3.2", "[Unboxing conversions](types.md#unboxing-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§4.3.1", "[Boxing conversions](types.md#boxing-conversionsexpressions.md#addition-operator)")
            s = s.Replace("§4.3", "[Boxing and unboxing](types.md#boxing-and-unboxingexpressions.md#addition-operator)")
            s = s.Replace("§4.2.7", "[Delegate types](types.md#delegate-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.2.6", "[Array types](types.md#array-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.2.5", "[Interface types](types.md#interface-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.2.4", "[The string type](types.md#the-string-typeexpressions.md#addition-operator)")
            s = s.Replace("§4.2.3", "[The dynamic type](types.md#the-dynamic-typeexpressions.md#addition-operator)")
            s = s.Replace("§4.2.2", "[The object type](types.md#the-object-typeexpressions.md#addition-operator)")
            s = s.Replace("§4.2.1", "[Class types](types.md#class-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.2", "[Reference types](types.md#reference-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.1.10", "[Nullable types](types.md#nullable-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.1.9", "[Enumeration types](types.md#enumeration-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.1.8", "[The bool type](types.md#the-bool-typeexpressions.md#addition-operator)")
            s = s.Replace("§4.1.7", "[The decimal type](types.md#the-decimal-typeexpressions.md#addition-operator)")
            s = s.Replace("§4.1.6", "[Floating point types](types.md#floating-point-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.1.5", "[Integral types](types.md#integral-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.1.4", "[Simple types](types.md#simple-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.1.3", "[Struct types](types.md#struct-typesexpressions.md#addition-operator)")
            s = s.Replace("§4.1.2", "[Default constructors](types.md#default-constructorsexpressions.md#addition-operator)")
            s = s.Replace("§4.1.1", "[The System.ValueType type](types.md#the-systemvaluetype-typeexpressions.md#addition-operator)")
            s = s.Replace("§4.1", "[Value types](types.md#value-typesexpressions.md#addition-operator)")
            s = s.Replace("§4", "[Types](types.md#typesexpressions.md#addition-operator)")
            s = s.Replace("§3.10", "[Execution order](basic-concepts.md#execution-orderexpressions.md#addition-operator)")
            s = s.Replace("§3.9", "[Automatic memory management](basic-concepts.md#automatic-memory-managementexpressions.md#addition-operator)")
            s = s.Replace("§3.8.1", "[Fully qualified names](basic-concepts.md#fully-qualified-namesexpressions.md#addition-operator)")
            s = s.Replace("§3.8", "[Namespace and type names](basic-concepts.md#namespace-and-type-namesexpressions.md#addition-operator)")
            s = s.Replace("§3.7.1.2", "[Hiding through inheritance](basic-concepts.md#hiding-through-inheritanceexpressions.md#addition-operator)")
            s = s.Replace("§3.7.1.1", "[Hiding through nesting](basic-concepts.md#hiding-through-nestingexpressions.md#addition-operator)")
            s = s.Replace("§3.7.1", "[Name hiding](basic-concepts.md#name-hidingexpressions.md#addition-operator)")
            s = s.Replace("§3.7", "[Scopes](basic-concepts.md#scopesexpressions.md#addition-operator)")
            s = s.Replace("§3.6", "[Signatures and overloading](basic-concepts.md#signatures-and-overloadingexpressions.md#addition-operator)")
            s = s.Replace("§3.5.4", "[Accessibility constraints](basic-concepts.md#accessibility-constraintsexpressions.md#addition-operator)")
            s = s.Replace("§3.5.3", "[Protected access for instance members](basic-concepts.md#protected-access-for-instance-membersexpressions.md#addition-operator)")
            s = s.Replace("§3.5.2", "[Accessibility domains](basic-concepts.md#accessibility-domainsexpressions.md#addition-operator)")
            s = s.Replace("§3.5.1", "[Declared accessibility](basic-concepts.md#declared-accessibilityexpressions.md#addition-operator)")
            s = s.Replace("§3.5", "[Member access](basic-concepts.md#member-accessexpressions.md#addition-operator)")
            s = s.Replace("§3.4.7", "[Delegate members](basic-concepts.md#delegate-membersexpressions.md#addition-operator)")
            s = s.Replace("§3.4.6", "[Array members](basic-concepts.md#array-membersexpressions.md#addition-operator)")
            s = s.Replace("§3.4.5", "[Interface members](basic-concepts.md#interface-membersexpressions.md#addition-operator)")
            s = s.Replace("§3.4.4", "[Class members](basic-concepts.md#class-membersexpressions.md#addition-operator)")
            s = s.Replace("§3.4.3", "[Enumeration members](basic-concepts.md#enumeration-membersexpressions.md#addition-operator)")
            s = s.Replace("§3.4.2", "[Struct members](basic-concepts.md#struct-membersexpressions.md#addition-operator)")
            s = s.Replace("§3.4.1", "[Namespace members](basic-concepts.md#namespace-membersexpressions.md#addition-operator)")
            s = s.Replace("§3.4", "[Members](basic-concepts.md#membersexpressions.md#addition-operator)")
            s = s.Replace("§3.3", "[Declarations](basic-concepts.md#declarationsexpressions.md#addition-operator)")
            s = s.Replace("§3.2", "[Application termination](basic-concepts.md#application-terminationexpressions.md#addition-operator)")
            s = s.Replace("§3.1", "[Application Startup](basic-concepts.md#application-startupexpressions.md#addition-operator)")
            s = s.Replace("§3", "[Basic concepts](basic-concepts.md#basic-conceptsexpressions.md#addition-operator)")
            s = s.Replace("§2.5.8.1", "[Pragma warning](lexical-structure.md#pragma-warningexpressions.md#addition-operator)")
            s = s.Replace("§2.5.8", "[Pragma directives](lexical-structure.md#pragma-directivesexpressions.md#addition-operator)")
            s = s.Replace("§2.5.7", "[Line directives](lexical-structure.md#line-directivesexpressions.md#addition-operator)")
            s = s.Replace("§2.5.6", "[Region directives](lexical-structure.md#region-directivesexpressions.md#addition-operator)")
            s = s.Replace("§2.5.5", "[Diagnostic directives](lexical-structure.md#diagnostic-directivesexpressions.md#addition-operator)")
            s = s.Replace("§2.5.4", "[Conditional compilation directives](lexical-structure.md#conditional-compilation-directivesexpressions.md#addition-operator)")
            s = s.Replace("§2.5.3", "[Declaration directives](lexical-structure.md#declaration-directivesexpressions.md#addition-operator)")
            s = s.Replace("§2.5.2", "[Pre-processing expressions](lexical-structure.md#pre-processing-expressionsexpressions.md#addition-operator)")
            s = s.Replace("§2.5.1", "[Conditional compilation symbols](lexical-structure.md#conditional-compilation-symbolsexpressions.md#addition-operator)")
            s = s.Replace("§2.5", "[Pre-processing directives](lexical-structure.md#pre-processing-directivesexpressions.md#addition-operator)")
            s = s.Replace("§2.4.5", "[Operators and punctuators](lexical-structure.md#operators-and-punctuatorsexpressions.md#addition-operator)")
            s = s.Replace("§2.4.4.6", "[The null literal](lexical-structure.md#the-null-literalexpressions.md#addition-operator)")
            s = s.Replace("§2.4.4.5", "[String literals](lexical-structure.md#string-literalsexpressions.md#addition-operator)")
            s = s.Replace("§2.4.4.4", "[Character literals](lexical-structure.md#character-literalsexpressions.md#addition-operator)")
            s = s.Replace("§2.4.4.3", "[Real literals](lexical-structure.md#real-literalsexpressions.md#addition-operator)")
            s = s.Replace("§2.4.4.2", "[Integer literals](lexical-structure.md#integer-literalsexpressions.md#addition-operator)")
            s = s.Replace("§2.4.4.1", "[Boolean literals](lexical-structure.md#boolean-literalsexpressions.md#addition-operator)")
            s = s.Replace("§2.4.4", "[Literals](lexical-structure.md#literalsexpressions.md#addition-operator)")
            s = s.Replace("§2.4.3", "[Keywords](lexical-structure.md#keywordsexpressions.md#addition-operator)")
            s = s.Replace("§2.4.2", "[Identifiers](lexical-structure.md#identifiersexpressions.md#addition-operator)")
            s = s.Replace("§2.4.1", "[Unicode character escape sequences](lexical-structure.md#unicode-character-escape-sequencesexpressions.md#addition-operator)")
            s = s.Replace("§2.4", "[Tokens](lexical-structure.md#tokensexpressions.md#addition-operator)")
            s = s.Replace("§2.3.3", "[White space](lexical-structure.md#white-spaceexpressions.md#addition-operator)")
            s = s.Replace("§2.3.2", "[Comments](lexical-structure.md#commentsexpressions.md#addition-operator)")
            s = s.Replace("§2.3.1", "[Line terminators](lexical-structure.md#line-terminatorsexpressions.md#addition-operator)")
            s = s.Replace("§2.3", "[Lexical analysis](lexical-structure.md#lexical-analysisexpressions.md#addition-operator)")
            s = s.Replace("§2.2.3", "[Syntactic grammar](lexical-structure.md#syntactic-grammarexpressions.md#addition-operator)")
            s = s.Replace("§2.2.2", "[Lexical grammar](lexical-structure.md#lexical-grammarexpressions.md#addition-operator)")
            s = s.Replace("§2.2.1", "[Grammar notation](lexical-structure.md#grammar-notationexpressions.md#addition-operator)")
            s = s.Replace("§2.2", "[Grammars](lexical-structure.md#grammarsexpressions.md#addition-operator)")
            s = s.Replace("§2.1", "[Programs](lexical-structure.md#programsexpressions.md#addition-operator)")
            s = s.Replace("§2", "[Lexical structure](lexical-structure.md#lexical-structureexpressions.md#addition-operator)")
            s = s.Replace("§1.12", "[Attributes](introduction.md#attributesexpressions.md#addition-operator)")
            s = s.Replace("§1.11", "[Delegates](introduction.md#delegatesexpressions.md#addition-operator)")
            s = s.Replace("§1.10", "[Enums](introduction.md#enumsexpressions.md#addition-operator)")
            s = s.Replace("§1.9", "[Interfaces](introduction.md#interfacesexpressions.md#addition-operator)")
            s = s.Replace("§1.8", "[Arrays](introduction.md#arraysexpressions.md#addition-operator)")
            s = s.Replace("§1.7", "[Structs](introduction.md#structsexpressions.md#addition-operator)")
            s = s.Replace("§1.6.7.6", "[Destructors](introduction.md#destructorsexpressions.md#addition-operator)")
            s = s.Replace("§1.6.7.5", "[Operators](introduction.md#operatorsexpressions.md#addition-operator)")
            s = s.Replace("§1.6.7.4", "[Events](introduction.md#eventsexpressions.md#addition-operator)")
            s = s.Replace("§1.6.7.3", "[Indexers](introduction.md#indexersexpressions.md#addition-operator)")
            s = s.Replace("§1.6.7.2", "[Properties](introduction.md#propertiesexpressions.md#addition-operator)")
            s = s.Replace("§1.6.7.1", "[Constructors](introduction.md#constructorsexpressions.md#addition-operator)")
            s = s.Replace("§1.6.7", "[Other function members](introduction.md#other-function-membersexpressions.md#addition-operator)")
            s = s.Replace("§1.6.6.5", "[Method overloading](introduction.md#method-overloadingexpressions.md#addition-operator)")
            s = s.Replace("§1.6.6.4", "[Virtual, override, and abstract methods](introduction.md#virtual-override-and-abstract-methodsexpressions.md#addition-operator)")
            s = s.Replace("§1.6.6.3", "[Static and instance methods](introduction.md#static-and-instance-methodsexpressions.md#addition-operator)")
            s = s.Replace("§1.6.6.2", "[Method body and local variables](introduction.md#method-body-and-local-variablesexpressions.md#addition-operator)")
            s = s.Replace("§1.6.6.1", "[Parameters](introduction.md#parametersexpressions.md#addition-operator)")
            s = s.Replace("§1.6.6", "[Methods](introduction.md#methodsexpressions.md#addition-operator)")
            s = s.Replace("§1.6.5", "[Fields](introduction.md#fieldsexpressions.md#addition-operator)")
            s = s.Replace("§1.6.4", "[Base classes](introduction.md#base-classesexpressions.md#addition-operator)")
            s = s.Replace("§1.6.3", "[Type parameters](introduction.md#type-parametersexpressions.md#addition-operator)")
            s = s.Replace("§1.6.2", "[Accessibility](introduction.md#accessibilityexpressions.md#addition-operator)")
            s = s.Replace("§1.6.1", "[Members](introduction.md#membersexpressions.md#addition-operator)")
            s = s.Replace("§1.6", "[Classes and objects](introduction.md#classes-and-objectsexpressions.md#addition-operator)")
            s = s.Replace("§1.5", "[Statements](introduction.md#statementsexpressions.md#addition-operator)")
            s = s.Replace("§1.4", "[Expressions](introduction.md#expressionsexpressions.md#addition-operator)")
            s = s.Replace("§1.3", "[Types and variables](introduction.md#types-and-variablesexpressions.md#addition-operator)")
            s = s.Replace("§1.2", "[Program structure](introduction.md#program-structureexpressions.md#addition-operator)")
            s = s.Replace("§1.1", "[Hello world](introduction.md#hello-worldexpressions.md#addition-operator)")
            s = s.Replace("§1", "[Introduction](introduction.md#introductionexpressions.md#addition-operator)")
            IO.File.WriteAllText(fn, s, Text.Encoding.UTF8)
        Next
    End Sub

    Sub Main()
        Dim args = Environment.GetCommandLineArgs
        Dim ifn = If(args.Length >= 2, args(1), "readme.md")

        If Not IO.File.Exists(ifn) OrElse
           Not IO.File.Exists("template.docx") OrElse
           IO.Directory.GetFiles(".", "*.g4").Length > 1 Then
            Console.Error.WriteLine("md2docx <filename>.md -- converts it to '<filename>.docx', based on 'template.docx'")
            Console.Error.WriteLine()
            Console.Error.WriteLine("If no file is specified:")
            Console.Error.WriteLine("    it looks for readme.md instead")
            Console.Error.WriteLine("If input file has a list with links of the form `* [Link](subfile.md)`:")
            Console.Error.WriteLine("   it converts the listed subfiles instead of <filename>.md")
            Console.Error.WriteLine("If the current directory contains one <grammar>.g4 file:")
            Console.Error.WriteLine("   it verifies all ```antlr blocks correspond, and also generates <grammar>.html")
            Console.Error.WriteLine("If 'template.docx' contains a Table of Contents:")
            Console.Error.WriteLine("   it replaces it with one based on the markdown (but page numbers aren't supported)")
            Environment.Exit(1)
        End If

        ' Read input file. If it contains a load of linked filenames, then read them instead.
        Dim readme = FSharp.Markdown.Markdown.Parse(IO.File.ReadAllText(ifn))
        Dim files = (From list In readme.Paragraphs.OfType(Of FSharp.Markdown.MarkdownParagraph.ListBlock)
                     Let items = list.Item2
                     From par In items
                     From spanpar In par.OfType(Of FSharp.Markdown.MarkdownParagraph.Span)
                     Let spans = spanpar.Item
                     From link In spans.OfType(Of FSharp.Markdown.MarkdownSpan.DirectLink)
                     Let url = link.Item2.Item1
                     Where url.EndsWith(".md", StringComparison.InvariantCultureIgnoreCase)
                     Select url).ToList.Distinct
        If files.Count = 0 Then files = {ifn}

        UpdateMDs(files)
        Return

        Dim md = MarkdownSpec.ReadFiles(files)


        ' Now md.Gramar contains the grammar as extracted out of the *.md files, and moreover has
        ' correct references to within the spec. We'll check that it has the same productions as
        ' in the corresponding ANTLR file
        Dim antlrfn = IO.Directory.GetFiles(".", "*.g4").FirstOrDefault
        If antlrfn IsNot Nothing Then
            Dim htmlfn = IO.Path.ChangeExtension(antlrfn, ".html")
            Dim grammar = Antlr.ReadFile(antlrfn)
            If Not grammar.AreProductionsSameAs(md.Grammar) Then Throw New Exception("Grammar mismatch")
            md.Grammar.Name = grammar.Name ' because grammar name is derived from antlrfn, and can't be known from markdown
            Html.WriteFile(md.Grammar, htmlfn)
            'Process.Start(htmlfn)
        End If

        ' Generate the Specification.docx file
        Dim fn = PickUniqueFilename(IO.Path.ChangeExtension(ifn, ".docx"))
        md.WriteFile("template.docx", fn)
        Process.Start(fn)

    End Sub


    Function PickUniqueFilename(suggestion As String) As String
        Dim base = IO.Path.GetFileNameWithoutExtension(suggestion)
        Dim ext = IO.Path.GetExtension(suggestion)

        Dim ifn = 0
        Do
            Dim fn = base & If(ifn = 0, "", CStr(ifn)) & ext
            If Not IO.File.Exists(fn) Then Return fn
            Try
                IO.File.Delete(fn) : Return fn
            Catch ex As Exception
            End Try
            ifn += 1
        Loop
    End Function

End Module

